// <auto-generated />
namespace ItLabs.FinkInformator.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seedupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seedupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201708101343068_Seed updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
